# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\CLion\CLion 2024.2.2\bin\cmake\win\x64\bin\cmake.exe"

# The command to remove a file.
RM = "D:\CLion\CLion 2024.2.2\bin\cmake\win\x64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\Nico T\Desktop\ProyectoPP3-main"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\Nico T\Desktop\ProyectoPP3-main"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	"D:\CLion\CLion 2024.2.2\bin\cmake\win\x64\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"D:\CLion\CLion 2024.2.2\bin\cmake\win\x64\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Nico T\Desktop\ProyectoPP3-main\CMakeFiles" "C:\Users\Nico T\Desktop\ProyectoPP3-main\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Nico T\Desktop\ProyectoPP3-main\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GestorProyectos

# Build rule for target.
GestorProyectos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 GestorProyectos
.PHONY : GestorProyectos

# fast build rule for target.
GestorProyectos/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/build
.PHONY : GestorProyectos/fast

Cliente.obj: Cliente.cpp.obj
.PHONY : Cliente.obj

# target to build an object file
Cliente.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Cliente.cpp.obj
.PHONY : Cliente.cpp.obj

Cliente.i: Cliente.cpp.i
.PHONY : Cliente.i

# target to preprocess a source file
Cliente.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Cliente.cpp.i
.PHONY : Cliente.cpp.i

Cliente.s: Cliente.cpp.s
.PHONY : Cliente.s

# target to generate assembly for a file
Cliente.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Cliente.cpp.s
.PHONY : Cliente.cpp.s

Desarrollador.obj: Desarrollador.cpp.obj
.PHONY : Desarrollador.obj

# target to build an object file
Desarrollador.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Desarrollador.cpp.obj
.PHONY : Desarrollador.cpp.obj

Desarrollador.i: Desarrollador.cpp.i
.PHONY : Desarrollador.i

# target to preprocess a source file
Desarrollador.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Desarrollador.cpp.i
.PHONY : Desarrollador.cpp.i

Desarrollador.s: Desarrollador.cpp.s
.PHONY : Desarrollador.s

# target to generate assembly for a file
Desarrollador.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Desarrollador.cpp.s
.PHONY : Desarrollador.cpp.s

Empleado.obj: Empleado.cpp.obj
.PHONY : Empleado.obj

# target to build an object file
Empleado.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Empleado.cpp.obj
.PHONY : Empleado.cpp.obj

Empleado.i: Empleado.cpp.i
.PHONY : Empleado.i

# target to preprocess a source file
Empleado.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Empleado.cpp.i
.PHONY : Empleado.cpp.i

Empleado.s: Empleado.cpp.s
.PHONY : Empleado.s

# target to generate assembly for a file
Empleado.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Empleado.cpp.s
.PHONY : Empleado.cpp.s

GerenteProyecto.obj: GerenteProyecto.cpp.obj
.PHONY : GerenteProyecto.obj

# target to build an object file
GerenteProyecto.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/GerenteProyecto.cpp.obj
.PHONY : GerenteProyecto.cpp.obj

GerenteProyecto.i: GerenteProyecto.cpp.i
.PHONY : GerenteProyecto.i

# target to preprocess a source file
GerenteProyecto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/GerenteProyecto.cpp.i
.PHONY : GerenteProyecto.cpp.i

GerenteProyecto.s: GerenteProyecto.cpp.s
.PHONY : GerenteProyecto.s

# target to generate assembly for a file
GerenteProyecto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/GerenteProyecto.cpp.s
.PHONY : GerenteProyecto.cpp.s

Proyecto.obj: Proyecto.cpp.obj
.PHONY : Proyecto.obj

# target to build an object file
Proyecto.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Proyecto.cpp.obj
.PHONY : Proyecto.cpp.obj

Proyecto.i: Proyecto.cpp.i
.PHONY : Proyecto.i

# target to preprocess a source file
Proyecto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Proyecto.cpp.i
.PHONY : Proyecto.cpp.i

Proyecto.s: Proyecto.cpp.s
.PHONY : Proyecto.s

# target to generate assembly for a file
Proyecto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Proyecto.cpp.s
.PHONY : Proyecto.cpp.s

Reporte_.obj: Reporte_.cpp.obj
.PHONY : Reporte_.obj

# target to build an object file
Reporte_.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Reporte_.cpp.obj
.PHONY : Reporte_.cpp.obj

Reporte_.i: Reporte_.cpp.i
.PHONY : Reporte_.i

# target to preprocess a source file
Reporte_.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Reporte_.cpp.i
.PHONY : Reporte_.cpp.i

Reporte_.s: Reporte_.cpp.s
.PHONY : Reporte_.s

# target to generate assembly for a file
Reporte_.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Reporte_.cpp.s
.PHONY : Reporte_.cpp.s

ReunionSeguimiento.obj: ReunionSeguimiento.cpp.obj
.PHONY : ReunionSeguimiento.obj

# target to build an object file
ReunionSeguimiento.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/ReunionSeguimiento.cpp.obj
.PHONY : ReunionSeguimiento.cpp.obj

ReunionSeguimiento.i: ReunionSeguimiento.cpp.i
.PHONY : ReunionSeguimiento.i

# target to preprocess a source file
ReunionSeguimiento.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/ReunionSeguimiento.cpp.i
.PHONY : ReunionSeguimiento.cpp.i

ReunionSeguimiento.s: ReunionSeguimiento.cpp.s
.PHONY : ReunionSeguimiento.s

# target to generate assembly for a file
ReunionSeguimiento.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/ReunionSeguimiento.cpp.s
.PHONY : ReunionSeguimiento.cpp.s

Tarea.obj: Tarea.cpp.obj
.PHONY : Tarea.obj

# target to build an object file
Tarea.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Tarea.cpp.obj
.PHONY : Tarea.cpp.obj

Tarea.i: Tarea.cpp.i
.PHONY : Tarea.i

# target to preprocess a source file
Tarea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Tarea.cpp.i
.PHONY : Tarea.cpp.i

Tarea.s: Tarea.cpp.s
.PHONY : Tarea.s

# target to generate assembly for a file
Tarea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Tarea.cpp.s
.PHONY : Tarea.cpp.s

Tester.obj: Tester.cpp.obj
.PHONY : Tester.obj

# target to build an object file
Tester.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Tester.cpp.obj
.PHONY : Tester.cpp.obj

Tester.i: Tester.cpp.i
.PHONY : Tester.i

# target to preprocess a source file
Tester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Tester.cpp.i
.PHONY : Tester.cpp.i

Tester.s: Tester.cpp.s
.PHONY : Tester.s

# target to generate assembly for a file
Tester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/Tester.cpp.s
.PHONY : Tester.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\GestorProyectos.dir\build.make CMakeFiles/GestorProyectos.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... GestorProyectos
	@echo ... Cliente.obj
	@echo ... Cliente.i
	@echo ... Cliente.s
	@echo ... Desarrollador.obj
	@echo ... Desarrollador.i
	@echo ... Desarrollador.s
	@echo ... Empleado.obj
	@echo ... Empleado.i
	@echo ... Empleado.s
	@echo ... GerenteProyecto.obj
	@echo ... GerenteProyecto.i
	@echo ... GerenteProyecto.s
	@echo ... Proyecto.obj
	@echo ... Proyecto.i
	@echo ... Proyecto.s
	@echo ... Reporte_.obj
	@echo ... Reporte_.i
	@echo ... Reporte_.s
	@echo ... ReunionSeguimiento.obj
	@echo ... ReunionSeguimiento.i
	@echo ... ReunionSeguimiento.s
	@echo ... Tarea.obj
	@echo ... Tarea.i
	@echo ... Tarea.s
	@echo ... Tester.obj
	@echo ... Tester.i
	@echo ... Tester.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

